Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Style/GuardClause:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ["describe", "context"]
